# Generated by Django 3.2.6 on 2021-08-14 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soju', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Bear',
        ),
    ]
