# Generated by Django 3.2.6 on 2021-08-14 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soju', '0002_rename_product_bear'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bear',
            new_name='Beer',
        ),
    ]
