# Generated by Django 3.2.6 on 2021-08-14 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soju', '0005_auto_20210814_2330'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Survey',
        ),
    ]
