# Generated by Django 3.2.6 on 2021-08-17 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soju', '0006_delete_survey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10)),
                ('password', models.CharField(max_length=64, verbose_name='Password')),
                ('registered', models.DateTimeField(auto_now_add=True, verbose_name='AddDate')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'db_table': 'user',
            },
        ),
        migrations.RenameField(
            model_name='beer',
            old_name='price',
            new_name='sanmi',
        ),
        migrations.AddField(
            model_name='beer',
            name='like',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='meta_description',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='re',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='s',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='star',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='beer',
            name='category',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterIndexTogether(
            name='beer',
            index_together=set(),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='like',
            name='user_like',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beer', to='soju.beer'),
        ),
        migrations.AddField(
            model_name='like',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='soju.user'),
        ),
        migrations.RemoveField(
            model_name='beer',
            name='slug',
        ),
    ]
