# Generated by Django 3.2.6 on 2021-08-17 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soju', '0009_userstar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='user_name',
        ),
    ]
