# Generated by Django 3.2.6 on 2021-08-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soju', '0010_rename_name_user_user_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'user'},
        ),
        migrations.AlterField(
            model_name='beer',
            name='like',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beer',
            name='sanmi',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='beer',
            name='star',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
