# Generated by Django 3.2.6 on 2021-08-18 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soju', '0012_auto_20210817_1342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beer',
            options={'ordering': ['category']},
        ),
    ]
