# Generated by Django 3.2.6 on 2021-08-18 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soju', '0013_alter_beer_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstar',
            name='ABV',
        ),
        migrations.RemoveField(
            model_name='userstar',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userstar',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userstar',
            name='s',
        ),
        migrations.RemoveField(
            model_name='userstar',
            name='sanmi',
        ),
        migrations.RemoveField(
            model_name='userstar',
            name='star',
        ),
        migrations.RemoveField(
            model_name='userstar',
            name='sugar',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='like',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='link',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='re',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='star',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Userstar',
        ),
    ]
