# Generated by Django 3.2.6 on 2021-08-18 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soju', '0014_auto_20210818_2109'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
