# Generated by Django 3.2.6 on 2021-08-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soju', '0015_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='ABV',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3),
        ),
    ]
