# Generated by Django 3.2.6 on 2021-08-18 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category1', models.CharField(max_length=20, null=True)),
                ('category2', models.CharField(max_length=20, null=True)),
                ('category3', models.CharField(max_length=20, null=True)),
                ('category4', models.CharField(max_length=20, null=True)),
                ('ABV1', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('ABV2', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('sugar', models.PositiveIntegerField()),
                ('sanmi', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
