# Generated by Django 3.2.6 on 2021-08-18 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='category1',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='category2',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='category3',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='category4',
        ),
    ]
