# Generated by Django 3.2.6 on 2021-08-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20210818_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='category',
            new_name='category1',
        ),
        migrations.AddField(
            model_name='survey',
            name='category2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='category3',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='category4',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
