# Generated by Django 3.2.6 on 2021-08-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20210818_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='sugar',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
