# Generated by Django 3.2.6 on 2021-08-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_alter_survey_sugar'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='sanmi',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='category',
            field=models.CharField(max_length=100, verbose_name='category'),
        ),
    ]
